spring:
  profiles:
    active: dev,native

  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/app-config

server:
  port: 7777

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/