services:
    page-profiles-db:
        image: postgres:15.3
        restart: always
        environment:
            POSTGRES_DB: 'page-profiles-db'
            POSTGRES_USER: 'develop'
            POSTGRES_PASSWORD: 'develop'
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - ./page-profiles-db:/var/lib/postgresql/data
        ports:
            - 5436:5432
