spring:

  application:
    name: catalog-server

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:7777"

server:
  #servlet:
  #  context-path: /catalog-server
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
