services:
  users-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'users-db'
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
    volumes:
      - ./users-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
      