services:
  users-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'catalog-db'
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
    volumes:
      - ./catalog-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
      