INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Guitarra');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Piano');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Batería');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Violín');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Saxofón');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Trompeta');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Bajo');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Flauta');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Ukelele');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Acordeón');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Clarinete');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Oboe');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Trombón');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Arpa');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Banjo');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Mandolina');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Contrabajo');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Sitar');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Didgeridoo');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Melódica');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Timbales');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Xilófono');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Vibráfono');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Marimba');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Glockenspiel');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Conga');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Bongos');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Djembe');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Tabla');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Kalimba');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Armónica');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Fagote');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Corneta');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Órgano');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Synthesizer');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Recorder');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Bagpipes');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Sax Tenor');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Sax Alto');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Sax Barítono');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Tuba');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Cornetín');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Claves');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Campanas');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Triangle');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Cuica');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Maracas');
INSERT INTO instruments (id, name) VALUES (gen_random_uuid(), 'Pandereta');

INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Jazz');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Rock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Pop');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Indie');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Clásica');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Reggae');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Blues');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Metal');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Electrónica');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Folklore');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Cuarteto');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Funk');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Soul');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'House');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Techno');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Salsa');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Cumbia');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Reggaetón');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Country');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'K-Pop');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Trap');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Bossa Nova');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Samba');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Tango');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Flamenco');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Bolero');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Ranchera');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Mariachi');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Merengue');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Bachata');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Trance');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Drum & Bass');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Dubstep');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Ambient');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Chillout');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'House Deep');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Tech House');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Hard Rock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Grunge');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Emo');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Post Rock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Avant-Garde');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Experimental');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Industrial');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Krautrock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Garage Rock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Punk');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Ska');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Post-Punk');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Folk Rock');
INSERT INTO styles (id, name) VALUES (gen_random_uuid(), 'Neo-Soul');

INSERT INTO page_Types (id, name) VALUES (gen_random_uuid(), 'Banda');
INSERT INTO page_Types (id, name) VALUES (gen_random_uuid(), 'General');
INSERT INTO page_Types (id, name) VALUES (gen_random_uuid(), 'Marca');
INSERT INTO page_Types (id, name) VALUES (gen_random_uuid(), 'Lugar');
INSERT INTO page_Types (id, name) VALUES (gen_random_uuid(), 'Creador de contenido');

INSERT INTO content_types (id, name) VALUES ('post', 'Posts');
INSERT INTO content_types (id, name) VALUES ('userprofile', 'Usuarios');
INSERT INTO content_types (id, name) VALUES ('pageprofile', 'Páginas');
INSERT INTO content_types (id, name) VALUES ('event', 'Eventos');

INSERT INTO post_types (id, name) VALUES (gen_random_uuid(), 'Market');
INSERT INTO post_types (id, name) VALUES (gen_random_uuid(), 'Job');
INSERT INTO post_types (id, name) VALUES (gen_random_uuid(), 'General');
