spring:
  application:
    name: gateway

  profiles:
    default: default

server:
  port: 4040

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
