spring:

    application:
        name: pages-server

    profiles:
        active: dev

    config:
        import: "optional:configserver:http://localhost:7777"

server:
    servlet:
        context-path: /pages-server
    port: 0

logging:
    level:
        org.springframework.cloud.gateway: DEBUG

eureka:
    instance:
        prefer-ip-address: true
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
