spring:

  application:
    name: auth-server

  profiles:
    default: dev

  config:
    import: "optional:configserver:http://localhost:7777"

  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}

  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}

server:
  servlet:
    context-path: /auth
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
