spring:
  datasource:
    username: develop
    password: develop
    url: jdbc:postgresql://localhost:5439/chat-db
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: "update"
      properties:
        hibernate.jdbc.time_zone: UTC

application:
  jwt:
    secret: "I'll see you on the dark side of the moon"
    expiration: 86400000
  internal:
    secret: "I'll see you on the dark side of the moon"
  host:
      url: http://localhost:4040
