spring:
    datasource:
        username: develop
        password: develop
        url: jdbc:postgresql://events-db:5432/events-db
        hikari:
            maximum-pool-size: 5
            connection-timeout: 20000
    jpa:
        hibernate:
            ddl-auto: "update"
        properties:
            hibernate:
                jdbc:
                    batch_size: 1000
                    time_zone: UTC
                order_inserts: true
                order_updates: true
                batch_versioned_data: true

application:
    internal:
        secret: "I'll see you on the dark side of the moon"
