spring:
  datasource:
    username: develop
    password: develop
    url: jdbc:postgresql://events-db:5437/events-db
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: "update"
      properties:
        hibernate.jdbc.time_zone: UTC

application:
  internal:
    secret: "I'll see you on the dark side of the moon"