spring:
  datasource:
    username: develop
    password: develop
    url: jdbc:postgresql://posts-db:5435/posts-db
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: "update"

application:
  internal:
    secret: "I'll see you on the dark side of the moon"