services:
  posts-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'posts-db'
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./posts-db:/var/lib/postgresql/data
    ports:
      - 5435:5432