services:
  events-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'events-db'
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./user-profiles-db:/var/lib/postgresql/data
    ports:
      - 5437:5432
      